feat: warn if driver is missing platforms
athombv/node-homey-lib pull request #319
Opened 2021-10-13 12:25 UTC by tjallingt

Missing `"platforms"` on a driver causes some very confusing behaviour when running an app on cloud.
We can't really error but we probably do want to warn that it is missing.

2021-10-13 13:20 UTC, WeeJeWel commented
This shouldn't be needed. The default is `[ "local" ]`

2021-10-13 13:37 UTC, tjallingt commented on lib/App/index.js
> +          console.warn(`Warning: drivers.${driver.id} doesn't have a 'platforms' property.`);
```suggestion
          console.warn(`Warning: drivers.${driver.id} doesn't have a 'platforms' property. The default is ["local"]`);
```

2021-11-01 12:01 UTC, WeeJeWel commented
I think it's better to only show this error when `App.platforms.includes('cloud')`.

2021-11-01 12:02 UTC, WeeJeWel requested changes
Only if App.platforms includes `cloud`.

2021-11-02 10:26 UTC, WeeJeWel approved these changes

2021-11-02 10:30 UTC, merged

2021-11-02 10:30 UTC, RobinBol approved these changes